[package]
name = "zanthe"
version = "0.1.0"
authors = ["Morgan Fogg"]
edition = "2018"
publish = false

[dependencies]
log = "0.4"
simplelog = "0.7"
rand = "0.7"
clap = "2.33"
itertools = "0.8"
crossterm = "0.16"
anyhow = "1.0"
backtrace = "0.3"
